### PR TITLE
Apply WASI support patch against ICU source tree

### PR DESCRIPTION
**Pull request by kateinoigakukun**
467631d2a7359c12bcf1c2254a3e797471d70b46 cherry-picks [ICU-22838 Add WebAssembly/WASI cross-compilation support](https://github.com/unicode-org/icu/pull/3067)

The original patch is still under review in the upstream ICU project, but it is needed to unblock the swift-foundation build on WebAssembly.

And also adjust CMakeLists.txt and Package.swift to disable timezone and dynamic loading features.

### CODE REVIEW

**Comment by iCharlesHu** [comment]
Hi @kateinoigakukun thanks for the patch! We recently upgraded our ICU to 74 and I'll reapply your patch on top of 74

**Comment by kateinoigakukun** [comment]
Reapplied my patch on the top of the latest main branch :)

**Comment by kateinoigakukun** [comment]
@swift-ci test

**Comment by kateinoigakukun** [comment]
Confirmed this change does not break other platform builds https://github.com/apple/swift-foundation/pull/823

**Review by MaxDesiatov — APPROVED** [review]

**Comment by iCharlesHu** [comment]
SwiftCorelibsFoundation and SwiftFoundation integration tests both passed! Merging now...

**Comment by kateinoigakukun** [comment]
Thanks!

**Pull request merged**
